// <auto-generated />
using System;
using ComputerBuilder.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ComputerBuilder.DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ComputerBuilder.DAL.Entities.BuildItem", b =>
                {
                    b.Property<int>("ComputerBuildId")
                        .HasColumnType("integer");

                    b.Property<int>("HardwareItemId")
                        .HasColumnType("integer");

                    b.HasKey("ComputerBuildId", "HardwareItemId");

                    b.HasIndex("HardwareItemId");

                    b.ToTable("BuildItem");
                });

            modelBuilder.Entity("ComputerBuilder.DAL.Entities.CompatibilityProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("HardwareItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PropertyType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HardwareItemId");

                    b.ToTable("compatibilityProperties");
                });

            modelBuilder.Entity("ComputerBuilder.DAL.Entities.ComputerBuild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("BuildDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<double>("TotalCost")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("computerBuilds");
                });

            modelBuilder.Entity("ComputerBuilder.DAL.Entities.HardwareItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("Cost")
                        .HasColumnType("double precision");

                    b.Property<string>("Description")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<int>("HardwareTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HardwareTypeId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("hardwareItems");
                });

            modelBuilder.Entity("ComputerBuilder.DAL.Entities.HardwareType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("hardwareTypes");
                });

            modelBuilder.Entity("ComputerBuilder.DAL.Entities.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("manufacturers");
                });

            modelBuilder.Entity("ComputerBuilder.DAL.Entities.BuildItem", b =>
                {
                    b.HasOne("ComputerBuilder.DAL.Entities.ComputerBuild", "ComputerBuild")
                        .WithMany("BuildItems")
                        .HasForeignKey("ComputerBuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerBuilder.DAL.Entities.HardwareItem", "HardwareItem")
                        .WithMany("BuildItems")
                        .HasForeignKey("HardwareItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ComputerBuilder.DAL.Entities.CompatibilityProperty", b =>
                {
                    b.HasOne("ComputerBuilder.DAL.Entities.HardwareItem", "HardwareItem")
                        .WithMany("PropertyList")
                        .HasForeignKey("HardwareItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ComputerBuilder.DAL.Entities.HardwareItem", b =>
                {
                    b.HasOne("ComputerBuilder.DAL.Entities.HardwareType", "HardwareType")
                        .WithMany("HardwareList")
                        .HasForeignKey("HardwareTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerBuilder.DAL.Entities.Manufacturer", "Manufacturer")
                        .WithMany("HardwareList")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
